"""fix_eliminado_por_id_set_null

Revision ID: 6fcdfc193fa3
Revises: 6031d16245ea
Create Date: 2026-05-28 12:25:30.717989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6fcdfc193fa3'
down_revision: Union[str, None] = '6031d16245ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('sesion_traduccion_eliminado_por_id_fkey', 'sesion_traduccion', type_='foreignkey')
    op.create_foreign_key(None, 'sesion_traduccion', 'usuario', ['eliminado_por_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sesion_traduccion', type_='foreignkey')
    op.create_foreign_key('sesion_traduccion_eliminado_por_id_fkey', 'sesion_traduccion', 'usuario', ['eliminado_por_id'], ['id'])
    # ### end Alembic commands ###