"""add_nombre_to_sesion_traduccion

Revision ID: 7cfbcb0b8a8b
Revises: 6fcdfc193fa3
Create Date: 2026-05-29 11:40:36.463884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7cfbcb0b8a8b'
down_revision: Union[str, None] = '6fcdfc193fa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sesion_traduccion', sa.Column('nombre', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sesion_traduccion', 'nombre')
    # ### end Alembic commands ###